version: "3.9"
services:
  database:
    image: postgres:14
    container_name: va_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_DB: videodb
    restart: always
    volumes:
      - "./pg:/var/lib/postgresql/data"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: va_server
    volumes:
      - "/app/node_modules"
      - ./server:/app
    ports:
      - "5000:5000"
    command: ["npm", "run", "dev"]
    restart: always
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: va_client
    volumes:
      - "/app/node_modules"
      - ./client:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    restart: always