version: "3.9"
services:
  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_DB: videodb
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - ./:/app
    ports:
      - "5000:5000"
    command: ["npm", "run", "dev"]